using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace GPS.CompiledJson.Tests;

public class SampleIncrementalSourceGeneratorTests
{
    private const string VectorRecordText = @"
namespace TestNamespace;

[Generators.CompiledJson]
public partial record Vector3
{
}";

    private const string ExpectedGeneratedRecordText = @"// <auto-generated/>

using System;
using System.Collections.Generic;

namespace TestNamespace;

partial record Vector3
{
    public IEnumerable<string> Report()
    {
        yield return $""EqualityContract:{this.EqualityContract}"";
    }
}
";

    [Fact]
    public void GenerateReportMethod()
    {
        // Create an instance of the source generator.
        var generator = new SampleIncrementalSourceGenerator();

        // Source generators should be tested using 'GeneratorDriver'.
        var driver = CSharpGeneratorDriver.Create(generator);

        // We need to create a compilation with the required source code.
        var compilation = CSharpCompilation.Create(nameof(SampleSourceGeneratorTests),
            new[] { CSharpSyntaxTree.ParseText(VectorRecordText) },
            new[]
            {
                // To support 'System.Attribute' inheritance, add reference to 'System.Private.CoreLib'.
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
            });

        // Run generators and retrieve all results.
        var runResult = driver.RunGenerators(compilation).GetRunResult();

        // All generated files can be found in 'RunResults.GeneratedTrees'.
        var generatedFileSyntax = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("Vector3.g.cs"));

        // Complex generators should be tested using text comparison.
        Assert.Equal(ExpectedGeneratedRecordText, generatedFileSyntax.GetText().ToString(),
            ignoreLineEndingDifferences: true);
    }
}